spawn:
  x: 0
  y: 100
  z: 0
  world: world
messages:
  notPlayer: Nur Spieler können diesen Befehl ausführen!
  playerNotOnline: Dieser Spieler ist gerade nicht online.
  teleported: Du wurdest zum Spawn teleportiert!
  playerTeleported: Der Spieler $PLAYER$ wurde zum Spawn teleportiert.
  spawnSet: Der Spawn wurde gesetzt.